# Generated by Django 3.1.3 on 2023-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_courier_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='size',
            field=models.CharField(default='small', max_length=20),
        ),
    ]
