# Generated by Django 3.1.3 on 2023-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230523_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(db_column='Количество', default=1),
        ),
    ]
