# Generated by Django 3.1.3 on 2023-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230523_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
