# Generated by Django 3.1.3 on 2023-05-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230523_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Адрес доставки посылки', max_length=255, verbose_name='Адрес доставки посылки'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_name',
            field=models.CharField(blank=True, help_text='Дополнительные данные', max_length=255, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_phone',
            field=models.CharField(blank=True, help_text='Номер для связи', max_length=50, verbose_name='Номер для связи'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_photo',
            field=models.ImageField(blank=True, help_text='Фото при доставке заказа', null=True, upload_to='job/delivery_photos/', verbose_name='Фото при доставке заказа'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(help_text='Описание', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='job',
            name='distance',
            field=models.FloatField(default=0, help_text='Расстояние', verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=0, help_text='Продолжительность', verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='Название', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(help_text='Фото товара', upload_to='job/photos/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Адрес получения посылки', max_length=255, verbose_name='Адрес получения посылки'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_name',
            field=models.CharField(blank=True, help_text='Дополнительные данные', max_length=255, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_phone',
            field=models.CharField(blank=True, help_text='Номер для связи', max_length=50, verbose_name='Номер для связи'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_photo',
            field=models.ImageField(blank=True, help_text='Фото при получении заказа', null=True, upload_to='job/pickup_photos/', verbose_name='Фото при получении заказа'),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.FloatField(default=0, help_text='Стоимость', verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Количество', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='job',
            name='size',
            field=models.CharField(choices=[('Размер упаковки не превышает 15х15х15см, вес не более 5 кг.', 'Размер упаковки не превышает 15х15х15см, вес не более 5 кг.'), ('Размер упаковки не превышает 40х40х26см, вес не более 15 кг.', 'Размер упаковки не превышает 40х40х26см, вес не более 15 кг.'), ('Размер упаковки не превышает 60х60х36см, вес не более 25 кг.', 'Размер упаковки не превышает 60х60х36см, вес не более 25 кг.')], default='Размер упаковки не превышает 15х15х15см, вес не более 5 кг.', help_text='Размер', max_length=70, verbose_name='Размер'),
        ),
    ]
