# Generated by Django 3.1.3 on 2023-05-23 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230523_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='job',
            name='courier',
            field=models.ForeignKey(blank=True, help_text='Курьер', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Заказ доставлен в', null=True, verbose_name='Заказ доставлен в '),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_lat',
            field=models.FloatField(default=0, help_text='Широта', verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='job',
            name='delivery_lng',
            field=models.FloatField(default=0, help_text='Долгота', verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickedup_at',
            field=models.DateTimeField(blank=True, help_text='Заказ взят в', null=True, verbose_name='Заказ взят в '),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Адрес получения посылки', max_length=255, verbose_name='Адрес получения посылки'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_lat',
            field=models.FloatField(default=0, help_text='Широта', verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_lng',
            field=models.FloatField(default=0, help_text='Долгота', verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('picking', 'Picking'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='creating', help_text='Статус', max_length=20, verbose_name='Статус'),
        ),
    ]
